export interface RadioStation {
  id: string;
  name: string;
  description: string | undefined;
  criteria: RadioStationCriteria[];
  createdAt: Date;
  updatedAt: Date;
  lastPlayed?: Date | null;
  isAutoGenerated?: boolean;
  isTemporary?: boolean;
}

export type RadioStationAttribute = 'artist' | 'album' | 'genre' | 'mood' | 'decade';

export interface RadioStationCriteria {
  attribute: RadioStationAttribute;
  value: string;
  weight: number; // 0-1 scale
}

export interface TrackScore {
  track: AudioTrack;
  score: number;
}