import React, { useEffect, useState } from 'react';
import SearchView, { performSearch } from './SearchView';
import { AudioTrack, MusicCacheService, MusicLibraryEntry, SearchResult } from '../services/musicCacheService';
import './MainView.css';
import { RadioStation, radioStationService } from '../services/radioStationService';

const cacheService = MusicCacheService.getInstance();

interface MainViewProps {
  onPlayTrack?: (track: AudioTrack) => void;
  onPlayStation?: (station: RadioStation, leadTrack?: MusicLibraryEntry) => void;
  onAlbumSelected?: (album: any) => void;
}

const MainView: React.FC<MainViewProps> = ({ onPlayTrack, onPlayStation, onAlbumSelected }) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState<SearchResult[]>([]);
  const [isSearching, setIsSearching] = useState(false);

  // State for suggested stations from the service
  const [suggestedStations, setSuggestedStations] = useState<RadioStation[]>([]);
  const [recentStations, setRecentStations] = useState<RadioStation[]>([]);
  const [isLoadingSuggestions, setIsLoadingSuggestions] = useState(true);

  // Initialize the cache service and fetch suggested stations when component mounts
  useEffect(() => {
    const initAndFetchSuggestions = async () => {
      try {
        await cacheService.initDB();
        let allStations = (await radioStationService.getAllStations())
          .filter(s => s.isAutoGenerated && !s.isAllMusic);
        // Select 5 random stations if available
        let randomStations: RadioStation[] = [];
        if (allStations.length > 0) {
          randomStations = allStations.sort(() => Math.random() - 0.5).slice(0, 5);
        }
        let playAll = await radioStationService.getDefaultStation();
        setSuggestedStations([playAll, ...randomStations]);
        // Get stations with lastPlayed, sort by lastPlayed (newest first), and cap to 6
        const recent = allStations
          .filter(station => station.lastPlayed)
          .sort((a, b) => {
            if (!a.lastPlayed || !b.lastPlayed) return 0;
            return b.lastPlayed.getTime() - a.lastPlayed.getTime();
          })
          .slice(0, 6);
        setRecentStations(recent);
      } catch (error) {
        console.error('Failed to initialize database:', error);
      }
      setIsLoadingSuggestions(false);
    };

    initAndFetchSuggestions();
  }, []);

  // Perform search when query changes
  useEffect(() => {
    if (searchQuery.trim() === '') {
      setSearchResults([]);
      setIsSearching(false);
      return;
    }

    const performSearchWrapper = async () => {
      await performSearch(
        cacheService,
        searchQuery,
        setSearchResults,
        setIsSearching
      );
    };

    // Add a small delay to avoid too frequent searches
    const timeoutId = setTimeout(performSearchWrapper, 100);
    return () => clearTimeout(timeoutId);
  }, [searchQuery]);



  return (
    <div className="radio-stations-view">
      <SearchView
        onSearchQueryChange={setSearchQuery}
        searchQuery={searchQuery}
        searchResults={searchResults}
        isSearching={isSearching}
        onPlayTrack={onPlayTrack}
        onPlayStation={onPlayStation}
        onAlbumSelected={onAlbumSelected}
      />

      {searchQuery.trim() === '' && !isLoadingSuggestions && <RenderStationTiles suggestedStations={suggestedStations} recentStations={recentStations} onPlayStation={onPlayStation} />}
    </div>
  )
}

// Render radio station tiles when no search query
const RenderStationTiles = ({ suggestedStations, recentStations, onPlayStation }: { suggestedStations: any[], recentStations: any[], onPlayStation?: ((station: RadioStation, leadTrack?: MusicLibraryEntry) => void) | undefined }) => {
  return (
    <>
      {/* Suggested Stations */}
      <div className="section-title">
        <h3>Suggested Stations</h3>
      </div>
      <div className="radio-station-grid">
          {suggestedStations.map((station) => (
            <div
              key={station.id}
              className="radio-station-card"
              onClick={() => onPlayStation && onPlayStation(station)}
            >
              {station.imagePath && (
                <img src={station.imagePath} alt={station.name} className="station-image" />
              )}
              <div className="station-label">{station.name.toUpperCase()}</div>
            </div>
          ))}
      </div>

      {/* Recent Stations */}
      <div className="section-title">
        <h3>Recently Played</h3>
      </div>
      <div className="radio-station-grid">
          {recentStations.map((station) => (
            <div
              key={station.id}
              className="radio-station-card"
              onClick={() => onPlayStation && onPlayStation(station)}
            >
              {station.imagePath && (
                <img src={station.imagePath} alt={station.name} className="station-image" />
              )}
              <div className="station-label">{station.name.toUpperCase()}</div>
            </div>
          ))}
      </div>
    </>
  );
};

export default MainView;